### ISSUE TITLE
fit_trees() unable to run due to IncompatibleClassChangeError

### ISSUE THREAD

**Issue by chrysania** [aehrc/VariantSpark#229]
- Tried to run the following command on VariantSpark version 0.5.2, Hail version 0.2.74, and Python version 3.9.16
```
rf_model = vshl.random_forest_model(y=mt.labels.Diagnosis,
                    x=mt.GT.n_alt_alleles(), 
                    covariates={'age':mt.labels.Age, 'APOE':mt.labels.APOE},
                    seed=13, mtry_fraction=0.05,
                    min_node_size=5, max_depth=10, imputation_type="mode")
rf_model.fit_trees(n_trees=100, batch_size=25)
```
and got this error message:
```
2023-04-10 06:37:37 Hail: INFO: Coerced sorted dataset
---------------------------------------------------------------------------
FatalError                                Traceback (most recent call last)
[<ipython-input-10-2ab3642e2dc8>](https://localhost:8080/#) in <cell line: 6>()
      4                     seed=13, mtry_fraction=0.05,
      5                     min_node_size=5, max_depth=10, imputation_type="mode")
----> 6 rf_model.fit_trees(n_trees=100, batch_size=25)

<decorator-gen-1819> in fit_trees(self, n_trees, batch_size)

3 frames
[/usr/local/lib/python3.9/dist-packages/hail/backend/py4j_backend.py](https://localhost:8080/#) in deco(*args, **kwargs)
     28                 raise FatalError('Error summary: %s' % (deepest,), error_id) from None
     29             else:
---> 30                 raise FatalError('%s\n\nJava stack trace:\n%s\n'
     31                                  'Hail version: %s\n'
     32                                  'Error summary: %s' % (deepest, full, hail.__version__, deepest), error_id) from None

FatalError: IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class au/csiro/variantspark/algo/TreeRepresentationFactory. Method 'au.csiro.variantspark.algo.TreeFeature $anonfun$createRepresentation$1(au.csiro.variantspark.algo.TreeRepresentationFactory, scala.Tuple2)' at index 37 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef

Java stack trace:
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class au/csiro/variantspark/algo/TreeRepresentationFactory. Method 'au.csiro.variantspark.algo.TreeFeature $anonfun$createRepresentation$1(au.csiro.variantspark.algo.TreeRepresentationFactory, scala.Tuple2)' at index 37 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at au.csiro.variantspark.algo.TreeRepresentationFactory.createRepresentation(TreeFeature.scala:31)
	at au.csiro.variantspark.algo.TreeRepresentationFactory.createRepresentation$(TreeFeature.scala:30)
	at au.csiro.variantspark.algo.DefTreeRepresentationFactory$.createRepresentation(StdTreeFeatures.scala:56)
	at au.csiro.variantspark.hail.methods.RFModel.$anonfun$fitTrees$2(RFModel.scala:131)
	at is.hail.expr.ir.ExecuteContext$.$anonfun$scoped$3(ExecuteContext.scala:47)
	at is.hail.utils.package$.using(package.scala:627)
	at is.hail.expr.ir.ExecuteContext$.$anonfun$scoped$2(ExecuteContext.scala:47)
	at is.hail.utils.package$.using(package.scala:627)
	at is.hail.annotations.RegionPool$.scoped(RegionPool.scala:17)
	at is.hail.expr.ir.ExecuteContext$.scoped(ExecuteContext.scala:46)
	at is.hail.backend.spark.SparkBackend.withExecuteContext(SparkBackend.scala:275)
	at au.csiro.variantspark.hail.methods.RFModel.$anonfun$fitTrees$1(RFModel.scala:75)
	at is.hail.utils.ExecutionTimer$.time(ExecutionTimer.scala:52)
	at is.hail.utils.ExecutionTimer$.logTime(ExecutionTimer.scala:59)
	at au.csiro.variantspark.hail.methods.RFModel.fitTrees(RFModel.scala:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)

Hail version: 0.2.74-0c3a74d12093
Error summary: IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class au/csiro/variantspark/algo/TreeRepresentationFactory. Method 'au.csiro.variantspark.algo.TreeFeature $anonfun$createRepresentation$1(au.csiro.variantspark.algo.TreeRepresentationFactory, scala.Tuple2)' at index 37 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
```

- The following dependencies were already installed
```
# Requirements for VariantSpark
#
# Development tools
Sphinx==3.3.1
sphinx-rtd-theme==0.5.0
nbsphinx==0.8.0
pylint==2.6.0
pytest==6.2.2
twine==3.2.0
# varspark dependencies
Jinja2==3.0.3
pandas==1.1.4
typedecorator==0.0.5
hail==0.2.74
pyspark==3.1.1
scipy==1.6.3
numpy==1.21.2
patsy==0.5.2
statsmodels==0.13.2
seaborn==0.11.2
```

**Comment by rocreguant** [comment]
Thanks for opening the issue. 
It seems there is a version mismatch somewhere.
I'll come back to you with an answer :)

**Comment by rocreguant** [comment]
Hi again,
I managed to reproduce the error. It's caused by inconsistencies with scala.
I'd assume that you're on a linux system so you can check if you have scala installed and if it's version 2.12. If you're unsure you can run `spark-shell` command and check. There you're going to see the scala and spark versions. Spark should be 3.1.X. If that's not working you may need to get scala by:
 Downloading the corresponding version
`wget https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz`
unzip it
`tar -xzf spark-3.1.2-bin-hadoop3.2.tgz`
and add to the bashrc (i.e. vim ~/.bashrc) the lines below at the end of the file with the correct path.
`export SPARK_HOME=/home/sparkuser/spark`
`export PATH=$PATH:$SPARK_HOME/bin`
and finally sourcing it:
`source .bashrc`

I hope it helped :)
