### ISSUE TITLE
Install on any machine throws ``` java.lang.IncompatibleClassChangeError```

### ISSUE THREAD

**Issue by surak** [aehrc/VariantSpark#232]
Tried 3 different operating systems and python versions and java versions, from python 3.8 to 3.10, with different versions of java and spark on different machines

Installing from source with Maven and from Pipy, both with and without Spark (then using `pip install variant-spark[spark]`).

The error when trying the examples is always the same:

```
share/variant-spark/examples/local_run-importance-it.sh 
/home/strube1/lixo/sc_venv_template/venv/bin/variant-spark --spark --master local -- importance -ff /home/strube1/lixo/sc_venv_template/venv/share/variant-spark/src/test/data/data-labels.csv -fc label -v -rn 2000 -rbs 50 -ro -sr 13 -ovn raw -on 0 -if /home/strube1/lixo/sc_venv_template/venv/share/variant-spark/src/test/data/data.csv -it stdcsv -io {},
Exception in thread "main" java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class au/csiro/pbdava/ssparkle/spark/SparkApp. Method 'java.lang.String $anonfun$spark$1(au.csiro.pbdava.ssparkle.spark.SparkApp)' at index 118 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at au.csiro.pbdava.ssparkle.spark.SparkApp.spark(SparkApp.scala:22)
	at au.csiro.pbdava.ssparkle.spark.SparkApp.spark$(SparkApp.scala:21)
	at au.csiro.variantspark.cli.ImportanceCmd.spark$lzycompute(ImportanceCmd.scala:23)
	at au.csiro.variantspark.cli.ImportanceCmd.spark(ImportanceCmd.scala:23)
	at au.csiro.pbdava.ssparkle.spark.SparkApp.sc(SparkApp.scala:26)
	at au.csiro.pbdava.ssparkle.spark.SparkApp.sc$(SparkApp.scala:26)
	at au.csiro.variantspark.cli.ImportanceCmd.sc$lzycompute(ImportanceCmd.scala:23)
	at au.csiro.variantspark.cli.ImportanceCmd.sc(ImportanceCmd.scala:23)
	at au.csiro.variantspark.cli.ImportanceCmd.run(ImportanceCmd.scala:62)
	at au.csiro.sparkle.common.args4j.ArgsApp.run(ArgsApp.java:46)
	at au.csiro.sparkle.cmd.CmdApp.runApp(CmdApp.java:9)
	at au.csiro.sparkle.cmd.CmdApp.runApp(CmdApp.java:18)
	at au.csiro.sparkle.cmd.MultiCmdApp.runCommandOrClass(MultiCmdApp.java:58)
	at au.csiro.sparkle.cmd.MultiCmdApp.run(MultiCmdApp.java:54)
	at au.csiro.sparkle.cmd.CmdApp.runApp(CmdApp.java:9)
	at au.csiro.sparkle.cmd.CmdApp.runApp(CmdApp.java:18)
	at au.csiro.pbdava.ssparkle.common.arg4j.AppRunner$.mains(AppRunner.scala:17)
	at au.csiro.variantspark.cli.VariantSparkApp$.main(VariantSparkApp.scala:25)
	at au.csiro.variantspark.cli.VariantSparkApp.main(VariantSparkApp.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1020)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
23/06/30 16:59:17 INFO ShutdownHookManager: Shutdown hook called
23/06/30 16:59:17 INFO ShutdownHookManager: Deleting directory /tmp/spark-db5d5750-38ff-406d-b92d-ce51e51a16a6
```

**Comment by rocreguant** [comment]
This should work on a unix-based system:
	•	wget https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz
	•	tar -xzf spark-3.1.2-bin-hadoop3.2.tgz
	•	vi ~/.bashrc
	•	# Add below lines at the end of the .bashrc file and use the correct path!!!!
	•	·      export SPARK_HOME=/home/sparkuser/spark
	•	·      export PATH=$PATH:$SPARK_HOME/bin
	•	source .bashrc
	•	sudo add-apt-repository ppa:webupd8team/java
	•	sudo apt-get install openjdk-8-jdk
	•	sudo apt install maven
	•	if you don’t have javac in /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/ then you need to create a symbolic link sudo ln -s /usr/bin/javac /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/javac
	•	conda environment py3.8, VS clone, and mvn install, install requirements, I did also a pip install variant-spark
